version: 0.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\*AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore
build:
  project: BotSpec.sln
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
test:
  assemblies: '**\*.Tests.dll'
artifacts:
- path: 'BotSpec.{version}*.nupkg'
notifications:
- provider: Email
  to:
  - brimble2010@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  api_key:
    secure: rj0fcpqzN3MYvb6VjP5Ic8U5ecIs/TfJAcTo3bg6xf8QRfXLQiDHMLkxMMdMjhi8